### ISSUE TITLE
It does not compile

### ISSUE THREAD

**Issue by Gronfi** [Purik/RxDelphi#1]
Hi!
I can't compile the test project. I attatch an image of the problem.
![image](https://user-images.githubusercontent.com/3635566/36422875-1e295afc-163e-11e8-878d-38105e5697e2.png)

**Comment by PavelMinenkov** [comment]
Hi!!!
What is your version of IDE?

**Comment by PavelMinenkov** [comment]
Oh, sorry. It is 10.2
Can you tell me Remote desktop access? I will try to help you

**Comment by Gronfi** [comment]
Hi!
Do you mean you need to access to my computer? If so, sorry but can’t do this ☹ because this computer belongs to a company and can’t be accessed from outside
Regards



 David Alcelay Elorriaga

     ULMA Handling Systems









Garagaltza 50 - Apdo. 67
20.560 Oñati (Gipuzkoa)
T: +34 943 782492
F: +34 943 782910
www.ulmahandling.com<http://www.ulmahandling.com/>

[cid:image006.png@01D1A16A.068C5340]<http://www.ulmahandling.com/>[cid:image007.png@01D1A16A.068C5340]<https://plus.google.com/+ULMAHandlingSystemsOñati> [cid:image008.png@01D1A16A.068C5340] <https://www.linkedin.com/company/ulma-handling-systems>  [cid:image009.png@01D1A16A.068C5340] <https://www.youtube.com/user/ulmahandlingsystems>





De: Павел [mailto:notifications@github.com]
Enviado el: martes, 20 de febrero de 2018 15:27
Para: Purik/RxDelphi
CC: David Alcelay; Author
Asunto: Re: [Purik/RxDelphi] It does not compile (#1)


Oh, sorry. It is 10.2
Can you tell me Remote desktop access?

**Comment by PavelMinenkov** [comment]
Yes, there is some problems, I think it is IDE bug, I build project in XE3 and I see same effect.
Allways I can solve this by next step:
1. You see you can not compile
2. Don't click on any area of IDE
3. Compile next time by pressing Shift+F9

**Comment by Gronfi** [comment]
Hi, those steps don’t work for me ☹



 David Alcelay Elorriaga

     ULMA Handling Systems









Garagaltza 50 - Apdo. 67
20.560 Oñati (Gipuzkoa)
T: +34 943 782492
F: +34 943 782910
www.ulmahandling.com<http://www.ulmahandling.com/>

[cid:image006.png@01D1A16A.068C5340]<http://www.ulmahandling.com/>[cid:image007.png@01D1A16A.068C5340]<https://plus.google.com/+ULMAHandlingSystemsOñati> [cid:image008.png@01D1A16A.068C5340] <https://www.linkedin.com/company/ulma-handling-systems>  [cid:image009.png@01D1A16A.068C5340] <https://www.youtube.com/user/ulmahandlingsystems>





De: Павел [mailto:notifications@github.com]
Enviado el: martes, 20 de febrero de 2018 23:20
Para: Purik/RxDelphi
CC: David Alcelay; Author
Asunto: Re: [Purik/RxDelphi] It does not compile (#1)


Yes, there is some problems, I think it is IDE bug, I build project in XE3 and I see same effect.
Allways I can solve this by next step:

  1.  You see you can not compile
  2.  Don't click on any area of IDE
  3.  Compile next time by pressing Shift+F9

**Comment by PavelMinenkov** [comment]
I can give access to my machine through TeamViewer
I'll try reproduce your issue on XE10
